source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.1.4'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# jquery
gem 'jquery-rails'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Listen
gem 'listen', '>= 3.0.5', '< 3.2'
# tzinfo
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
